elixir-toolshed/toolshed

lib/my_helpers/nerves.ex, mix.exs
This will make integrating
[this](https://github.com/elixir-lang/elixir/issues/8063)
issue easier later on, and also makes `MIX_TARGET` env var
less magic.
=> Use Mix.Project.config()

lib/toolshed/net.ex
Occasionally, my RPi0W will include a sit0 network interface when calling `:inet.getifaddrs()`. This will return a result that looks something like the below:
```
{:ok,
[
...
{'sit0',
[flags: [], hwaddr: [0, 0, 0, 0]]},
...
]}
```
Because the `hwaddr` list only includes 4 values, the following exception is thrown when Toolshed tries to format the values:
```
** (ArgumentError) argument error
(stdlib) :io.format(#PID<0.668.0>, '    hwaddr ~2.16.0b:~2.16.0b:~2.16.0b:~2.16.0b:~2.16.0b:~2.16.0b~n', [0, 0, 0, 0])
```
This change allows the `addr` list to be any length (although the most likely lengths are 4 or 6).
Open to any suggestions to make this better, since I am admittedly an elixir/nerves/networking n00b. 😺
=> Allow varied length hwaddr lists in ifconfig

lib/toolshed/nerves.ex, mix.exs
This fixes compile time warnings 
```
==> toolshed
Compiling 7 files (.ex)
warning: function Nerves.Runtime.reboot/0 is undefined (module Nerves.Runtime is not available)
lib/toolshed/nerves.ex:32
```
It also doest require toolshed to know about "MIX_TARGET".
=> Add nerves_runtime as an optional dependency

mix.exs
This will prevent `toolshed` from building `nerves_runtime` and instead just exclude it from xref checks.
=> Exclude Nerves.Runtime from xref

lib/toolshed.ex, lib/toolshed/http.ex, mix.exs
These utilities all require an Internet connection to work. `weather` is
convenient for seeing where a Nerves device is (via GeoIP) and what the
weather is there. `qr_encode` is useful for copying chunks of data like
serial numbers to your phone, and `pastebin` is useful for sharing logs
and other text.
=> Add weather, qr_encode, and pastebin

lib/toolshed.ex, lib/toolshed/multicast.ex, test/multicast_test.exs
This utility is useful to debugging multicast issues where you want to
see what multicast addresses have active subscriptions. This is all from
the Linux kernel's point of view.
=> Add multicast_addresses/0

lib/toolshed/autocomplete.ex, test/toolshed/autocomplete_test.exs
Previously, path completion only worked when string fragments started
with `/` and `.`. Now it works for relative paths that start with the
directory or file name.
This change also switches from `File.ls` to `Path.wildcard` which seems
to simplify the code too.
=> Fix path completion without initial dot

lib/toolshed/autocomplete.ex, test/toolshed/autocomplete_test.exs
If you typed `/*<tab>`, `Path.wildcard/2` was being called with `"/**"`
which would traverse the whole file system. This commit stops this and
other ways to mess up `Path.wildcard/2` via tab completion.
=> Ignore wildcards from user on path completion

lib/toolshed/unix.ex, test/support/test_file.doc, test/toolshed/unix_test.exs
It also add alittle information to the cat helper function definition to
indicate it prints the content of a file.
=> This adds a unit test for the cat helper function.

test/toolshed/unix_test.exs
This is add unit test for the grep/2 function used to search for
a given pattern in a specified file(s)
=> Add unit test for the grep helper function

test/toolshed/unix_test.exs
This adds unit test for already existing Toolshed.Unix.uptime/0 which
returns the current uptime
=> Add unit test for uptime helper function

lib/toolshed.ex, test/toolshed_test.exs
This is needed to prevent crashing when a command writes non-unicode values to stdout.
=> Update cmd/1 to use `binstream` instead of `stream`

lib/toolshed.ex, lib/toolshed/http.ex
This helper doesn't seem to be used much in practice. There's still a
need to be able to easily transfer data, but posting to a third party
site that never deletes posts isn't the most comfortable for many
people.
=> Remove pastebin helper

test/toolshed_test.exs
The `echo` command varies more between platforms and it turned out to
not accept the `-e` parameter on OSX. This switches the tests to use the
more portable `printf` command which doesn't have the issue.
=> Replace echo with printf for portability

lib/toolshed.ex, lib/toolshed/log.ex, mix.exs, test/toolshed/log_test.exs
These are convenience functions for sending log messages to the current
IEx session. They reuse the Elixir console logger backend, but configure
it to report to the current group leader so that it works well with the
IEx prompt. Additionally, it monitors the group leader so that if it
goes away (like by terminating an ssh session), the logger backend will
be cleaned up.
The functionality here is similar to that provided by the `RingLogger`
library's `attach` and `detach` functions. These, however, are primarily
convenience functions for configuring the Elixir console logger backend.
=> Add log_attach and log_detach

lib/toolshed/net.ex, test/toolshed/net_test.exs
We recently needed the ability to ping IPv6 addresses due to using a type of network that doesn't support IPv4, so it seemed like a good opportunity to add this to Toolshed. This PR makes a small change to host resolution so that it attempts to resolve addresses for both `:inet` (IPv4) and `:inet6` (IPv6) before giving up. If both address families are available the IPv4 address is used, which should maintain backwards compatibility when pinging services on the Internet.
=> Add ability to ping IPv6 addresses

lib/toolshed/top.ex, lib/toolshed/top/report.ex, lib/toolshed/top/server.ex, test/toolshed/top/report_test.exs
This changes top so that it uses the current terminal's size (unless overridden) to 
determine how many rows to show.
A change made at the same time is to condense the I/O to one call to
IO.write. This should hopefully minimize flickering.
Fixes #90
=> Pass rows/cols to top; reduce IO

lib/toolshed/top.ex, lib/toolshed/top/processes.ex, lib/toolshed/top/report.ex, lib/toolshed/top/server.ex, test/toolshed/top/report_test.exs
I think that the `Elixir.` is pretty much implied with the capital
letter for the module. Removing it lets you see more of the module name
due to the limited column width.
=> top: remove Elixir. from module names

lib/toolshed.ex, lib/toolshed/history.ex, test/toolshed/history_test.exs
The purpose of the history command is to list out all of the previous
commands typed at the IEx prompt. This is nice when you want to see what
you did and refer to old commands. This information is in the group
leader, but inconvenient. This command fixes that.
=> Add a history command

lib/toolshed/net.ex
This lets you "ping" a port other than 80. Example:
```elixir
iex> ping "example,com", port: 53
...
```
=> Add port option to ping command

lib/toolshed/tcp_ping.ex, test/toolshed/tcp_ping_test.exs
This prints out the port number with the IP address that's being used.
It should make it more obvious that the `:port` option is working.
It looks like this:
```
iex> ping "google.com"
Press enter to stop
Response from google.com (172.217.9.206:80): time=17.686ms
Response from google.com (172.217.9.206:80): time=12.247ms
iex> ping "google.com", port: 443
Press enter to stop
Response from google.com (172.217.15.78:443): time=15.068ms
```
=> Be more explicit about port used in ping

.circleci/config.yml, README.md, lib/toolshed/autocomplete.ex, test/toolshed/autocomplete_test.exs
The path completion code was improved and merged into Elixir 1.13 so
it's not needed any more!
This removes it at compile-time so that it's still available for anyone
using Elixir 1.12 and earlier. Elixir 1.13 users get to use the better
built-in code.
=> Remove path completion on Elixir 1.13

lib/toolshed/http.ex
`wttr.in` is always redirecting to https. This needs `:ssl`, so verify
that it's available. Also switch the URL from http to https since it's
going to happen anyway.
https is not verified. This is not ideal, but probably not the end of
the world for getting the weather.
=> Ensure :ssl is loaded for weather/0

.circleci/config.yml, lib/toolshed/top/processes.ex, mix.exs
* remove deprecated `:race_conditions` dialyzer option
* Add new `:missing_return` and `:extra_return` dialyzer options
* Update Elixir/Erlang CI versions
=> Support OTP 25

lib/toolshed.ex, lib/toolshed/http.ex, lib/toolshed/utils.ex, lib/toolshed/weather.ex, test/toolshed/http_test.exs, test/toolshed/weather_test.exs
@fhunleth I tentatively prototyped https://github.com/elixir-toolshed/toolshed/issues/125 with https://github.com/elixir-toolshed/toolshed/issues/60 in mind.
- extract `weather/0` command from `Toolshed.HTTP`, newly creating `Toolshed.Weather`
- extract `check_app/1` helper from `Toolshed.HTTP`, newly creating `Toolshed.Utils`
- catch `:exit` signal that potentially occurs when `:httpc` server crashes
- rescue unexpected responses
- I was able to recreate two types of potential errors on my local machine
- `:https` server crashing, which throws `:exit`
- `:https` responds with unexpected response, which is currently anything but `{:ok, {_, _, _}}`
- I have trouble wording errors so it would be great if you come up with better messages.
- resolves …
=> Improve weather/0

lib/toolshed.ex, test/toolshed_test.exs
This pull request resolves https://github.com/elixir-toolshed/toolshed/issues/131, also https://github.com/elixir-toolshed/toolshed/issues/58.
- Do delegation instead of importing sub directory functions
- Test all the public functions are accessible via `Toolshed` module
When `Nerves.Runtime` is loaded, Nerves-specific functions are loaded.
In the generic Elixir environment, Nerves-specific functions are not loaded.
The API reference will look like this.
=> Do delegation to make all function available from top-level Toolshed

lib/toolshed.ex
Currently options in delegations are required, but they should be optional. I forgot to add default `[]` in https://github.com/elixir-toolshed/toolshed/pull/132.
- give default options `[]` to applicable `defdelegate` definitions.
=> Add default options [] to defdelegate's

lib/toolshed.ex, test/toolshed_test.exs
Currently `h/1` helper does not show useful info for individual functions due to delegation (https://github.com/elixir-toolshed/toolshed/pull/132). 
per discussed with @fhunleth
=> Add custom `h/1` macro so that it prints docs for delegated functions

lib/toolshed.ex, test/toolshed_test.exs
A few functions have wrong params since https://github.com/elixir-toolshed/toolshed/pull/132. Seemingly they are working properly but they cannot accept options.
=> Correct function params in delegation

lib/toolshed.ex
Since Toolshed is being sneaky with its `h/1` enhancements, make it show
the `h/1` help that IEx provides already.
=> Forward h/1 help and hide from exdoc

lib/toolshed/cat.ex, lib/toolshed/date.ex, lib/toolshed/grep.ex, lib/toolshed/history.ex, lib/toolshed/hostname.ex, lib/toolshed/http.ex, lib/toolshed/ifconfig.ex, lib/toolshed/lsof.ex, lib/toolshed/lsusb.ex, lib/toolshed/nslookup.ex, lib/toolshed/ping.ex, lib/toolshed/top.ex, lib/toolshed/tping.ex, lib/toolshed/tree.ex, lib/toolshed/uptime.ex, lib/toolshed/weather.ex
We'd like to discourage users from calling functions outside of the
`Toolshed` module. However, we'd also like to have the documentation for
the helper functions exist with the implementation. We can do that for
`h/1`, but not with `ex_doc`. Since `ex_doc` will give lots of warnings
for `@moduledoc false`, just leave it blank. The real documentation
should be on the function anyway.
=> Remove most module docs

lib/toolshed/top.ex
This PR hides the `:ok` return value when calling the `top` command.
=> Hide return value from top

lib/toolshed/weather.ex
This is a minor improvement for handling unexpected errors running `weather` command.
Currently when the Internet connection is not available, `httpc` seems to cause this internal `MatchError`, which looks cryptic from the user perspective.
We can rescue it and control what to show for this error.
- Related https://github.com/elixir-toolshed/toolshed/pull/130
=> Rescue httpc's internal MatchError

lib_src/core/httpget.ex
The 5 second default is pretty short, so this makes it longer and adds
the ability to make it even longer.
=> httpget: add timeout option and default to 30s

README.md, lib_src/core/speed_test.ex, mix.exs, test/toolshed/speed_test_test.exs, test/toolshed_test.exs
This checks how fast it can download a big file from dl.nerves-project.org or how much it can download in 5 seconds. It's not the best speed test, but it can give a quick idea whether the connection is terrible or not. This originates out of a speed test that we've been using at work.
Options to the speed test include specifying a different URL (both as an option and via application environment so users can default to a self-hosted file), specifying an ifname, and specifying a different max duration.
[![asciicast](https://asciinema.org/a/m1RjXPWfsTw8jpVws6gtzKB5z.svg)](https://asciinema.org/a/m1RjXPWfsTw8jpVws6gtzKB5z)
=> Add a simple speed test

lib_src/core/geo.ex, test/toolshed/geo_test.exs
httpc defaults to infinite timeouts. Since whenwhere servers should always
respond quickly so that they can be used for time purposes, make the
timeout default to 10s. This is much longer than anything anyone should
see in practice and also significantly better than waiting forever.
=> Don't let geo requests take forever
